---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.6.2

platforms:
- name: ubuntu-13.04
  driver_config:
    box: opscode_ubuntu-13.04_provisionerless
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box

suites:
- name: default
  run_list: ["recipe[sample-app]"]
  attributes: {}
