language: ruby
rvm:
  - 1.9.3
before_script:
  - mkdir .chef
  - |
    cat <<EOF > .chef/knife.rb
    cache_type 'BasicFile'
    cache_options(:path => "#{ENV['HOME']}/.chef/checksums")
    EOF
script:
  - rake test
